// app/qa-rating.tsx
import AsyncStorage from "@react-native-async-storage/async-storage";
import Slider from "@react-native-community/slider";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import { MotiView } from "moti";
import { useState } from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useTheme } from "../context/ThemeContext";

import {
  getUserProfiles,
  saveBrewRating,
  savePourProfile,
} from "../src/backend/api/database";
import { getSessionUser } from "../src/backend/auth/session";
import { calculateNewProfile } from "../src/backend/core/algorithm";
import { PourProfile } from "../src/models/types";
import { GradientButton } from "../src/components/auth/AuthControls";
import BeanConfetti from "../src/components/BeanConfetti";
import HeartCupIcon from "../src/components/HeartCupIcon";
import ScreenShell from "../src/components/ScreenShell";
import {
  Accent,
  Glass,
  Motion,
  Pop,
  Radii,
  SoftShadow,
} from "../src/constants/DesignSystem";

export default function QARatingScreen() {
  const router = useRouter();
  const { colors, theme } = useTheme();
  const isDark = theme === "dark";
  const glass = isDark ? Glass.dark : Glass.light;
  const pop = isDark ? Pop.dark : Pop.light;
  const accent = isDark ? Accent.dark : Accent.light;

  const [step, setStep] = useState<1 | 2>(1);
  const [score, setScore] = useState(16); // Enjoyment rating (1-20)
  const [strength, setStrength] = useState("Perfect");
  const [savedUserId, setSavedUserId] = useState<string>("unknown-user");

  const trackBgColor = isDark ? "rgba(255,255,255,0.15)" : "rgba(148,102,86,0.2)";

  const handleContinue = async () => {
    try {
      const user = await getSessionUser();
      const realUserId = user?.sub || "unknown-user";
      setSavedUserId(realUserId);

      // --- THE FIX: Match the exact ID generated by the database! ---
      const targetRecipeId = `${realUserId}_ai-optimized`;

      // 1. Fetch the exact current profile from the DB using the matched ID
      const profiles = await getUserProfiles(realUserId);
      const currentProfileUsed = profiles.find(
        (p) => p.profileId === targetRecipeId,
      ) || {
        profileId: targetRecipeId,
        userId: realUserId,
        name: "My Perfect Cup",
        targetTemp: 200,
        grindSize: 15,
        waterVolume: 250,
        coffeeWeight: 20,
        bloomTime: 30,
        dispenseRate: 3.5,
        isDefault: false,
      };

      const strengthMapped =
        strength === "Too Weak"
          ? "Too weak"
          : strength === "Too Strong"
            ? "Too strong"
            : "Just right";

      // --- RECORD PARAMETERS IN HISTORY LOG ---
      await saveBrewRating({
        userId: realUserId,
        profileId: currentProfileUsed.profileId,
        rating: score,
        perceivedStrength: strengthMapped,
        targetTemp: currentProfileUsed.targetTemp,
        grindSize: currentProfileUsed.grindSize,
        coffeeWeight: currentProfileUsed.coffeeWeight,
        waterVolume: currentProfileUsed.waterVolume,
      });

      // LEARNING LOGIC ---
      const optimizedRecipe = calculateNewProfile(
        currentProfileUsed as PourProfile,
        score,
        strengthMapped,
      );

      // --- THE FIX: Re-apply the exact matched ID before saving ---
      optimizedRecipe.profileId = targetRecipeId;
      optimizedRecipe.name = "My Perfect Cup";

      const newBitternessLevel = Math.max(
        1,
        Math.min(20, optimizedRecipe.targetTemp - 190),
      );
      await AsyncStorage.setItem(
        "user_coffee_pref",
        newBitternessLevel.toString(),
      );

      // Overwrite the existing profile in AWS instead of making a new one
      await savePourProfile(optimizedRecipe);
      console.log("Cup successfully updated in AWS!");
    } catch (error) {
      console.error("Failed to sync feedback with AWS:", error);
    }

    setStep(2);
  };

  const cardStyle = {
    backgroundColor: glass.surface,
    borderColor: glass.border,
    ...SoftShadow,
  };

  return (
    <ScreenShell
      title="Feedback"
      onBack={() => (step === 2 ? setStep(1) : router.back())}
      contentStyle={styles.content}
    >
      {step === 1 ? (
        <>
          <MotiView
            from={{ opacity: 0, translateY: 16 }}
            animate={{ opacity: 1, translateY: 0 }}
            transition={Motion.spring}
            style={[styles.card, cardStyle]}
          >
            <Text style={[styles.questionText, { color: colors.text }]}>
              From 1 to 20, how much did you enjoy the drink?
            </Text>
            <Text style={[styles.scoreText, { color: pop }]}>{score}</Text>
            <Slider
              style={{ width: "100%", height: 40 }}
              minimumValue={1}
              maximumValue={20}
              step={1}
              value={score}
              onValueChange={setScore}
              minimumTrackTintColor={pop}
              maximumTrackTintColor={trackBgColor}
              thumbTintColor={pop}
            />
          </MotiView>

          <MotiView
            from={{ opacity: 0, translateY: 16 }}
            animate={{ opacity: 1, translateY: 0 }}
            transition={{ ...Motion.spring, delay: 120 }}
            style={[styles.card, cardStyle]}
          >
            <Text style={[styles.questionText, { color: colors.text }]}>
              How was the strength of your coffee?
            </Text>
            <View style={styles.pillContainer}>
              {["Too Weak", "Perfect", "Too Strong"].map((option) => {
                const isActive = strength === option;
                return (
                  <TouchableOpacity
                    key={option}
                    activeOpacity={0.85}
                    onPress={() => setStrength(option)}
                    style={[
                      styles.pill,
                      { borderColor: isActive ? "transparent" : glass.border },
                      !isActive && { backgroundColor: "rgba(255,255,255,0.55)" },
                    ]}
                  >
                    {isActive && (
                      <LinearGradient
                        colors={[pop, accent]}
                        start={{ x: 0, y: 0 }}
                        end={{ x: 1, y: 0 }}
                        style={StyleSheet.absoluteFill}
                      />
                    )}
                    <Text
                      style={[
                        styles.pillText,
                        { color: isActive ? "#fff" : colors.text },
                      ]}
                    >
                      {option}
                    </Text>
                  </TouchableOpacity>
                );
              })}
            </View>
          </MotiView>

          <View style={{ flex: 1 }} />
          <GradientButton label="Continue" onPress={handleContinue} />
        </>
      ) : (
        <View style={styles.recommendationBlock}>
          <BeanConfetti colors={[pop, accent, "#E1B09C"]} />
          <MotiView
            from={{ opacity: 0, scale: 0.4 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={Motion.spring}
          >
            <HeartCupIcon width={150} />
          </MotiView>
          <Text style={[styles.recommendTitle, { color: colors.text }]}>
            Thanks for your feedback!
          </Text>
          <Text style={[styles.recommendSub, { color: colors.subtext }]}>
            The machine learned from your rating and automatically adjusted
            parameters for your next "My Perfect Cup" brew.
          </Text>
          <GradientButton
            label="Go Back Home"
            onPress={() => router.replace("/(tabs)/home")}
          />
        </View>
      )}
    </ScreenShell>
  );
}

const styles = StyleSheet.create({
  content: { paddingHorizontal: 24, paddingBottom: 24, paddingTop: 8, gap: 18 },
  card: {
    borderRadius: Radii.xl,
    borderWidth: 1,
    padding: 22,
  },
  questionText: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 14,
    textAlign: "center",
  },
  scoreText: {
    fontSize: 56,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 6,
  },
  pillContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
  },
  pill: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: Radii.pill,
    borderWidth: 1,
    overflow: "hidden",
  },
  pillText: { fontSize: 15, fontWeight: "800" },
  recommendationBlock: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  recommendTitle: {
    fontFamily: "serif",
    fontSize: 28,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 10,
  },
  recommendSub: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 18,
    lineHeight: 24,
  },
});
