[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Set the Serial Monitor speed to match our code
monitor_speed = 115200

; Automatically download the JSON library
lib_deps = 
	bblanchon/ArduinoJson@^6.21.3