// app/qa-rating.tsx
import AsyncStorage from "@react-native-async-storage/async-storage";
import Slider from "@react-native-community/slider";
import { useRouter } from "expo-router";
import { StatusBar } from "expo-status-bar";
import { ArrowLeft } from "lucide-react-native";
import { useState } from "react";
import {
  SafeAreaView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { useTheme } from "../context/ThemeContext";

import {
  getUserProfiles,
  saveBrewRating,
  savePourProfile,
} from "../src/backend/api/database";
import { getSessionUser } from "../src/backend/auth/session";
import { calculateNewProfile } from "../src/backend/core/algorithm";
import { PourProfile } from "../src/models/types";

export default function QARatingScreen() {
  const router = useRouter();
  const { colors, theme } = useTheme();
  const isDark = theme === "dark";

  const [step, setStep] = useState<1 | 2>(1);
  const [score, setScore] = useState(12); // Enjoyment rating (1-15)
  const [strength, setStrength] = useState("Perfect");
  const [savedUserId, setSavedUserId] = useState<string>("unknown-user");

  const bgColor = isDark ? colors.background : "#FFF1E5";
  const textColor = isDark ? colors.text : "#9C4400";
  const subtextColor = isDark ? colors.subtext : "#896D59";
  const btnBgColor = isDark ? colors.primaryButton : "#FFDEBA";
  const btnTextColor = isDark ? "#F0CEAB" : "#000000";
  const trackBgColor = isDark ? "#333333" : "#E5E5E5";

  const handleContinue = async () => {
    try {
      const user = await getSessionUser();
      const realUserId = user?.sub || "unknown-user";
      setSavedUserId(realUserId);

      // --- THE FIX: Match the exact ID generated by the database! ---
      const targetRecipeId = `${realUserId}_ai-optimized`;

      // 1. Fetch the exact current profile from the DB using the matched ID
      const profiles = await getUserProfiles(realUserId);
      const currentProfileUsed = profiles.find(
        (p) => p.profileId === targetRecipeId,
      ) || {
        profileId: targetRecipeId,
        userId: realUserId,
        name: "My Perfect Cup",
        targetTemp: 200,
        grindSize: 15,
        waterVolume: 250,
        coffeeWeight: 20,
        bloomTime: 30,
        dispenseRate: 3.5,
        isDefault: false,
      };

      const strengthMapped =
        strength === "Too Weak"
          ? "Too weak"
          : strength === "Too Strong"
            ? "Too strong"
            : "Just right";

      // --- RECORD PARAMETERS IN HISTORY LOG ---
      await saveBrewRating({
        userId: realUserId,
        profileId: currentProfileUsed.profileId,
        rating: score,
        perceivedStrength: strengthMapped,
        targetTemp: currentProfileUsed.targetTemp,
        grindSize: currentProfileUsed.grindSize,
        coffeeWeight: currentProfileUsed.coffeeWeight,
        waterVolume: currentProfileUsed.waterVolume,
      });

      // --- AI LEARNING LOGIC ---
      const optimizedRecipe = calculateNewProfile(
        currentProfileUsed as PourProfile,
        score,
        strengthMapped,
      );

      // --- THE FIX: Re-apply the exact matched ID before saving ---
      optimizedRecipe.profileId = targetRecipeId;
      optimizedRecipe.name = "My Perfect Cup";

      const newBitternessLevel = Math.max(
        1,
        Math.min(20, optimizedRecipe.targetTemp - 190),
      );
      await AsyncStorage.setItem(
        "user_coffee_pref",
        newBitternessLevel.toString(),
      );

      // Overwrite the existing profile in AWS instead of making a new one
      await savePourProfile(optimizedRecipe);
      console.log("AI-Optimized Cup successfully updated in AWS!");
    } catch (error) {
      console.error("Failed to sync feedback with AWS:", error);
    }

    setStep(2);
  };

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: bgColor }]}>
      <StatusBar style={isDark ? "light" : "dark"} />

      <View style={styles.topBar}>
        <TouchableOpacity
          style={[styles.backButton, { backgroundColor: btnBgColor }]}
          onPress={() => (step === 2 ? setStep(1) : router.back())}
          activeOpacity={0.8}
        >
          <ArrowLeft color={btnTextColor} size={24} />
        </TouchableOpacity>
        <Text style={[styles.title, { color: textColor }]}>Feedback</Text>
        <View style={{ width: 44 }} />
      </View>

      <View style={styles.content}>
        {step === 1 ? (
          <>
            <View style={styles.questionBlock}>
              <Text style={[styles.questionText, { color: textColor }]}>
                From 1 to 15, how much did you enjoy the drink?
              </Text>
              <Text style={[styles.scoreText, { color: textColor }]}>
                {score}
              </Text>
              <Slider
                style={{ width: "100%", height: 40 }}
                minimumValue={1}
                maximumValue={15}
                step={1}
                value={score}
                onValueChange={setScore}
                minimumTrackTintColor={btnBgColor}
                maximumTrackTintColor={trackBgColor}
                thumbTintColor={btnBgColor}
              />
            </View>

            <View style={styles.questionBlock}>
              <Text style={[styles.questionText, { color: textColor }]}>
                How was the strength of your coffee?
              </Text>
              <View style={styles.pillContainer}>
                {["Too Weak", "Perfect", "Too Strong"].map((option) => {
                  const isActive = strength === option;
                  return (
                    <TouchableOpacity
                      key={option}
                      style={[
                        styles.pill,
                        {
                          backgroundColor: isActive
                            ? btnBgColor
                            : "transparent",
                          borderColor: btnBgColor,
                          borderWidth: 2,
                        },
                      ]}
                      onPress={() => setStrength(option)}
                    >
                      <Text
                        style={[
                          styles.pillText,
                          { color: isActive ? btnTextColor : textColor },
                        ]}
                      >
                        {option}
                      </Text>
                    </TouchableOpacity>
                  );
                })}
              </View>
            </View>

            <TouchableOpacity
              style={[
                styles.primaryBtn,
                { backgroundColor: btnBgColor, marginTop: "auto" },
              ]}
              onPress={handleContinue}
            >
              <Text style={[styles.primaryBtnText, { color: btnTextColor }]}>
                Continue
              </Text>
            </TouchableOpacity>
          </>
        ) : (
          <View style={styles.recommendationBlock}>
            <Text style={[styles.recommendTitle, { color: textColor }]}>
              Thanks for your feedback!
            </Text>
            <Text style={[styles.recommendSub, { color: subtextColor }]}>
              The machine learned from your rating and automatically adjusted
              parameters for your next "My Perfect Cup" brew.
            </Text>
            <TouchableOpacity
              style={[
                styles.primaryBtn,
                { backgroundColor: btnBgColor, marginTop: 20 },
              ]}
              onPress={() => router.replace("/(tabs)/home")}
            >
              <Text style={[styles.primaryBtnText, { color: btnTextColor }]}>
                Go Back Home
              </Text>
            </TouchableOpacity>
          </View>
        )}
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 15,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  title: { fontSize: 24, fontWeight: "800", fontFamily: "serif" },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingBottom: 40,
    paddingTop: 20,
  },
  questionBlock: { marginBottom: 40 },
  questionText: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 20,
    textAlign: "center",
  },
  scoreText: {
    fontSize: 48,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 10,
  },
  pillContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
  },
  pill: { paddingVertical: 12, paddingHorizontal: 20, borderRadius: 25 },
  pillText: { fontSize: 16, fontWeight: "700" },
  recommendationBlock: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  recommendTitle: {
    fontSize: 28,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 15,
  },
  recommendSub: {
    fontSize: 16,
    textAlign: "center",
    marginBottom: 30,
    lineHeight: 24,
  },
  primaryBtn: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
  },
  primaryBtnText: { fontSize: 18, fontWeight: "800" },
});
